# Blog settings
permalink: /:title


# My variables
name: Dmitry Manannikov
description: All about good parts of web developing
meta_description: "Best way dev, all about good parts of web developing"
domain_name: 'http://slonoed.net'
google_analytics: 'UA-58504841-1'
email: email@slonoed.net


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

baseurl: /
blogurl: /

# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
