name: Best way dev 
description: All about good parts of web developing
meta_description: "Best way dev, all about good parts of web developing"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 10
paginate_path: "/page/:num"
baseurl: /
domain_name: 'http://slonoed.net'
google_analytics: 'UA-58504841-1'

# Details for the RSS feed generator
url:            'http://slonoed.net'
author:         'Dmitry Manannikov'

permalink: "/:categories/:title"
